#!/usr/bin/env python3
"""Clean up files generated by STDF analysis scripts."""

import os
import shutil

ROOT = os.path.dirname(os.path.abspath(__file__))

REMOVE_PATTERNS = [
    ("*.csv", "CSV output files"),
]

REMOVE_DIRS = [
    "__pycache__",
]

REMOVE_EXTS = [
    ".pyc",
]


def main():
    removed = 0

    csv_files = [f for f in os.listdir(ROOT) if f.endswith(".csv")]
    for f in csv_files:
        path = os.path.join(ROOT, f)
        os.remove(path)
        print(f"  removed  {path}")
        removed += 1

    for dirpath, dirnames, filenames in os.walk(ROOT):
        if ".git" in dirpath.split(os.sep):
            continue
        for d in list(dirnames):
            if d in REMOVE_DIRS:
                path = os.path.join(dirpath, d)
                shutil.rmtree(path)
                print(f"  removed  {path}/")
                removed += 1
        for fn in filenames:
            if any(fn.endswith(ext) for ext in REMOVE_EXTS):
                path = os.path.join(dirpath, fn)
                os.remove(path)
                print(f"  removed  {path}")
                removed += 1

    if removed:
        print(f"\nCleaned up {removed} item(s).")
    else:
        print("Nothing to clean.")


if __name__ == "__main__":
    main()
